import slugify from "slugify";
import type { Category } from "@/db/categories";
import type { Model } from "@/db/schema/models";
import { MODEL_SLUGIFY_OPTIONS } from "@/lib/slugify";
import type { Prettify } from "@/types";

type SeedModel = Prettify<
  Omit<Model, "userId" | "likes" | "categorySlug"> & {
    categorySlug: Category["slug"];
  }
>;

export const modelsData: SeedModel[] = [
  {
    categorySlug: "toys-games",
    dateAdded: new Date("2023-03-15T14:30:00Z"),
    description: "A detailed dragon model with movable joints and wings",
    image: "/img/models/1.jpg",
    name: "Articulated Dragon",
    slug: slugify("Articulated Dragon", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "household",
    dateAdded: new Date("2023-06-22T09:15:00Z"),
    description: "Geometric planter perfect for small succulents",
    image: "/img/models/2.jpg",
    name: "Succulent Planter",
    slug: slugify("Succulent Planter", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "props-cosplay",
    dateAdded: new Date("2023-09-05T16:45:00Z"),
    description: "Sci-fi inspired helmet for costume making",
    image: "/img/models/3.jpg",
    name: "Cosplay Helmet",
    slug: slugify("Cosplay Helmet", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "education",
    dateAdded: new Date("2023-11-30T11:20:00Z"),
    description: "Scale model of the solar system for classroom use",
    image: "/img/models/4.jpg",
    name: "Educational Solar System",
    slug: slugify("Educational Solar System", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "art",
    dateAdded: new Date("2024-01-18T13:40:00Z"),
    description: "Modern art piece with flowing curves",
    image: "/img/models/5.jpg",
    name: "Abstract Sculpture",
    slug: slugify("Abstract Sculpture", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "tools",
    dateAdded: new Date("2024-03-07T10:25:00Z"),
    description: "Customizable holder for workshop tools",
    image: "/img/models/6.jpg",
    name: "Tool Holder",
    slug: slugify("Tool Holder", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "miniatures",
    dateAdded: new Date("2024-05-12T15:50:00Z"),
    description: "Detailed warrior miniature for tabletop gaming",
    image: "/img/models/7.jpg",
    name: "Fantasy Miniature",
    slug: slugify("Fantasy Miniature", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "fashion",
    dateAdded: new Date("2024-07-25T08:35:00Z"),
    description: "Tool for creating custom jewelry",
    image: "/img/models/8.jpg",
    name: "Bracelet Maker",
    slug: slugify("Bracelet Maker", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "3d-printer",
    dateAdded: new Date("2024-09-14T12:15:00Z"),
    description: "Enhancement parts for 3D printer performance",
    image: "/img/models/9.jpg",
    name: "Printer Upgrade Kit",
    slug: slugify("Printer Upgrade Kit", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "hobby-diy",
    dateAdded: new Date("2024-11-03T17:40:00Z"),
    description: "Collection of tools for gardening enthusiasts",
    image: "/img/models/10.jpg",
    name: "Garden Tool Set",
    slug: slugify("Garden Tool Set", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "toys-games",
    dateAdded: new Date("2023-02-28T14:20:00Z"),
    description: "Modern interpretation of classic chess pieces",
    image: "/img/models/11.jpg",
    name: "Chess Set",
    slug: slugify("Chess Set", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "household",
    dateAdded: new Date("2023-05-17T11:30:00Z"),
    description: "Modular system for wall storage",
    image: "/img/models/12.jpg",
    name: "Wall Organizer",
    slug: slugify("Wall Organizer", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "props-cosplay",
    dateAdded: new Date("2023-08-09T16:05:00Z"),
    description: "Fantasy sword for costume play",
    image: "/img/models/13.jpg",
    name: "Prop Sword",
    slug: slugify("Prop Sword", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "education",
    dateAdded: new Date("2023-10-22T09:45:00Z"),
    description: "Educational model of molecular structures",
    image: "/img/models/14.jpg",
    name: "Molecular Model",
    slug: slugify("Molecular Model", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "art",
    dateAdded: new Date("2024-01-05T15:25:00Z"),
    description: "Decorative wall panels with geometric patterns",
    image: "/img/models/15.jpg",
    name: "Geometric Wall Art",
    slug: slugify("Geometric Wall Art", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "tools",
    dateAdded: new Date("2024-02-19T10:50:00Z"),
    description: "Custom handles for precision screwdrivers",
    image: "/img/models/16.jpg",
    name: "Screwdriver Set",
    slug: slugify("Screwdriver Set", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "miniatures",
    dateAdded: new Date("2024-04-30T13:15:00Z"),
    description: "Detailed dragon for tabletop gaming",
    image: "/img/models/17.jpg",
    name: "Dragon Miniature",
    slug: slugify("Dragon Miniature", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "fashion",
    dateAdded: new Date("2024-06-14T08:40:00Z"),
    description: "Set of geometric earring designs",
    image: "/img/models/18.jpg",
    name: "Earring Collection",
    slug: slugify("Earring Collection", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "3d-printer",
    dateAdded: new Date("2024-08-27T12:55:00Z"),
    description: "Enhanced cooling solution for 3D printers",
    image: "/img/models/19.jpg",
    name: "Cooling System",
    slug: slugify("Cooling System", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "hobby-diy",
    dateAdded: new Date("2024-10-11T17:20:00Z"),
    description: "DIY birdhouse with modern design",
    image: "/img/models/20.jpg",
    name: "Birdhouse Kit",
    slug: slugify("Birdhouse Kit", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "toys-games",
    dateAdded: new Date("2023-01-25T14:10:00Z"),
    description: "Articulated robot with moving parts",
    image: "/img/models/21.jpg",
    name: "Robot Toy",
    slug: slugify("Robot Toy", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "household",
    dateAdded: new Date("2023-04-08T11:35:00Z"),
    description: "Customizable drawer organization system",
    image: "/img/models/22.jpg",
    name: "Kitchen Organizer",
    slug: slugify("Kitchen Organizer", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "props-cosplay",
    dateAdded: new Date("2023-07-21T16:00:00Z"),
    description: "Base template for custom costume masks",
    image: "/img/models/23.jpg",
    name: "Mask Template",
    slug: slugify("Mask Template", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "education",
    dateAdded: new Date("2023-09-30T09:25:00Z"),
    description: "Educational DNA double helix model",
    image: "/img/models/24.jpg",
    name: "DNA Model",
    slug: slugify("DNA Model", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "art",
    dateAdded: new Date("2023-12-13T15:50:00Z"),
    description: "Contemporary vase with unique patterns",
    image: "/img/models/25.jpg",
    name: "Modern Vase",
    slug: slugify("Modern Vase", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "tools",
    dateAdded: new Date("2024-02-26T10:15:00Z"),
    description: "Custom sized wrench collection",
    image: "/img/models/26.jpg",
    name: "Wrench Set",
    slug: slugify("Wrench Set", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "miniatures",
    dateAdded: new Date("2024-04-09T13:40:00Z"),
    description: "Detailed medieval castle for gaming",
    image: "/img/models/27.jpg",
    name: "Castle Miniature",
    slug: slugify("Castle Miniature", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "fashion",
    dateAdded: new Date("2024-06-22T08:05:00Z"),
    description: "Customizable pendant template",
    image: "/img/models/28.jpg",
    name: "Pendant Design",
    slug: slugify("Pendant Design", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "3d-printer",
    dateAdded: new Date("2024-08-05T12:30:00Z"),
    description: "Enhanced extruder mechanism",
    image: "/img/models/29.jpg",
    name: "Extruder Upgrade",
    slug: slugify("Extruder Upgrade", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "hobby-diy",
    dateAdded: new Date("2024-10-18T17:55:00Z"),
    description: "Modern stand for indoor plants",
    image: "/img/models/30.jpg",
    name: "Plant Stand",
    slug: slugify("Plant Stand", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "toys-games",
    dateAdded: new Date("2023-01-12T14:00:00Z"),
    description: "Complex mechanical puzzle toy",
    image: "/img/models/31.jpg",
    name: "Puzzle Cube",
    slug: slugify("Puzzle Cube", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "household",
    dateAdded: new Date("2023-03-25T11:25:00Z"),
    description: "Shower organization solution",
    image: "/img/models/32.jpg",
    name: "Bathroom Caddy",
    slug: slugify("Bathroom Caddy", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "props-cosplay",
    dateAdded: new Date("2023-06-08T16:50:00Z"),
    description: "Detailed costume armor segment",
    image: "/img/models/33.jpg",
    name: "Armor Piece",
    slug: slugify("Armor Piece", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "education",
    dateAdded: new Date("2023-08-21T09:15:00Z"),
    description: "Interactive atomic structure model",
    image: "/img/models/34.jpg",
    name: "Atom Model",
    slug: slugify("Atom Model", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "art",
    dateAdded: new Date("2023-11-04T15:40:00Z"),
    description: "Abstract wall mounted artwork",
    image: "/img/models/35.jpg",
    name: "Wall Sculpture",
    slug: slugify("Wall Sculpture", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "tools",
    dateAdded: new Date("2024-01-17T10:05:00Z"),
    description: "Precise measurement device",
    image: "/img/models/36.jpg",
    name: "Measuring Tool",
    slug: slugify("Measuring Tool", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "miniatures",
    dateAdded: new Date("2024-03-30T13:30:00Z"),
    description: "Detailed tree for miniature landscapes",
    image: "/img/models/37.jpg",
    name: "Fantasy Tree",
    slug: slugify("Fantasy Tree", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "fashion",
    dateAdded: new Date("2024-06-12T08:55:00Z"),
    description: "Customizable ring designs",
    image: "/img/models/38.jpg",
    name: "Ring Collection",
    slug: slugify("Ring Collection", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "3d-printer",
    dateAdded: new Date("2024-08-25T12:20:00Z"),
    description: "Optimized cooling fan design",
    image: "/img/models/39.jpg",
    name: "Print Fan",
    slug: slugify("Print Fan", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "hobby-diy",
    dateAdded: new Date("2024-11-08T17:45:00Z"),
    description: "Wall-mounted tool organization system",
    image: "/img/models/40.jpg",
    name: "Tool Rack",
    slug: slugify("Tool Rack", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "toys-games",
    dateAdded: new Date("2023-02-01T14:35:00Z"),
    description: "Poseable character figure",
    image: "/img/models/41.jpg",
    name: "Action Figure",
    slug: slugify("Action Figure", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "household",
    dateAdded: new Date("2023-04-14T11:00:00Z"),
    description: "Desk cable organization solution",
    image: "/img/models/42.jpg",
    name: "Cable Manager",
    slug: slugify("Cable Manager", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "props-cosplay",
    dateAdded: new Date("2023-07-27T16:25:00Z"),
    description: "Fantasy shield for costumes",
    image: "/img/models/43.jpg",
    name: "Prop Shield",
    slug: slugify("Prop Shield", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "education",
    dateAdded: new Date("2023-10-10T09:50:00Z"),
    description: "Detailed biological cell model",
    image: "/img/models/44.jpg",
    name: "Cell Model",
    slug: slugify("Cell Model", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "art",
    dateAdded: new Date("2023-12-23T15:15:00Z"),
    description: "Decorative lamp with unique design",
    image: "/img/models/45.jpg",
    name: "Art Lamp",
    slug: slugify("Art Lamp", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "tools",
    dateAdded: new Date("2024-03-07T10:40:00Z"),
    description: "Fine detail work tool",
    image: "/img/models/46.jpg",
    name: "Precision Tool",
    slug: slugify("Precision Tool", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "miniatures",
    dateAdded: new Date("2024-05-20T14:05:00Z"),
    description: "Detailed landscape for gaming",
    image: "/img/models/47.jpg",
    name: "Terrain Piece",
    slug: slugify("Terrain Piece", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "fashion",
    dateAdded: new Date("2024-07-03T08:30:00Z"),
    description: "Modern accessory design",
    image: "/img/models/48.jpg",
    name: "Fashion Accessory",
    slug: slugify("Fashion Accessory", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "3d-printer",
    dateAdded: new Date("2024-09-16T12:55:00Z"),
    description: "Stabilizing platform for 3D printers",
    image: "/img/models/49.jpg",
    name: "Printer Stand",
    slug: slugify("Printer Stand", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "hobby-diy",
    dateAdded: new Date("2024-11-29T17:20:00Z"),
    description: "Modular garden planter system",
    image: "/img/models/50.jpg",
    name: "Planter Box",
    slug: slugify("Planter Box", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "toys-games",
    dateAdded: new Date("2023-01-15T14:45:00Z"),
    description: "Compatible construction toy set",
    image: "/img/models/51.jpg",
    name: "Building Blocks",
    slug: slugify("Building Blocks", MODEL_SLUGIFY_OPTIONS),
  },
  {
    categorySlug: "household",
    dateAdded: new Date("2023-03-28T11:10:00Z"),
    description: "Customizable shelving solution",
    image: "/img/models/52.jpg",
    name: "Shelf System",
    slug: slugify("Shelf System", MODEL_SLUGIFY_OPTIONS),
  },
];
